# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# NOTE: R-specific hooks are temporarily disabled due to macOS compilation issues
# To enable them, uncomment the section below and ensure R packages can compile
# See .pre-commit-config-full.yaml for the full configuration

# # R-specific hooks from lorenzwalthert/precommit
# - repo: https://github.com/lorenzwalthert/precommit
#   rev: v0.4.3
#   hooks:
#     # Style files using styler
#     - id: style-files
#       args: [--style_pkg=styler, --style_fun=tidyverse_style]
#     # Update documentation with roxygen2
#     - id: roxygenize
#     # Keep DESCRIPTION tidy
#     - id: use-tidy-description
#     # Spell check
#     - id: spell-check
#       args: [--wordlist=inst/WORDLIST]
#     # Code quality checks with lintr
#     - id: lintr
#       args: [--warn-only]
#     # Ensure README.Rmd and README.md are in sync
#     - id: readme-rmd-rendered
#     # Check for parsable R code
#     - id: parsable-R
#     # No browser() statements
#     - id: no-browser-statement
#     # No debug() statements
#     - id: no-debug-statement
#     # Check dependencies are in DESCRIPTION
#     - id: deps-in-desc

# Standard pre-commit hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    # Remove trailing whitespace
    - id: trailing-whitespace
      exclude: |
        (?x)^(
          .*\.md$
        )$
    # Ensure files end with newline
    - id: end-of-file-fixer
      exclude: |
        (?x)^(
          .*\.Rd$
        )$
    # Check for files that would conflict on case-insensitive filesystems
    - id: check-case-conflict
    # Check for merge conflicts
    - id: check-merge-conflict
    # Check YAML files are parseable
    - id: check-yaml
    # Prevent large files from being committed
    - id: check-added-large-files
      args: ['--maxkb=500']
    # Sort entries in .Rbuildignore
    - id: file-contents-sorter
      files: '^\.Rbuildignore$'

# Local hooks for R-specific artifacts
- repo: local
  hooks:
    - id: forbid-to-commit
      name: Don't commit common R artifacts
      entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
      language: fail
      files: '\.(Rhistory|RData|Rds|rds)$'
      exclude: |
        (?x)^(
          inst/extdata/.*|
          data/.*
        )$

# CI configuration for pre-commit.ci
ci:
  # Automatic updates of hook versions
  autoupdate_schedule: monthly
  # Skip hooks that require R in CI (if problematic)
  # skip: [roxygenize]
  # Autofix PRs
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
    
    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_branch: '' 