# Docker Compose override for GitHub Codespaces
# Optimizes the development environment for cloud-based development

version: '3.8'

services:
  hetid-dev:
    # Override build context for Codespaces
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        BUILDKIT_INLINE_CACHE: 1

    # Codespaces-specific environment variables
    environment:
      - DISABLE_AUTH=true
      - ROOT=true
      - RSTUDIO_WHICH_R=/usr/local/bin/R
      - R_LIBS_USER=/usr/local/lib/R/site-library
      - GITHUB_CODESPACES=true
      - CODESPACE_NAME=${CODESPACE_NAME:-hetid-dev}
      - GITHUB_USER=${GITHUB_USER:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}

    # Port mappings for Codespaces
    ports:
      - "8787:8787"  # RStudio Server
      - "3838:3838"  # Shiny apps
      - "8080:8080"  # Additional web services

    # Volume mounts optimized for Codespaces
    volumes:
      # Workspace mount (handled by devcontainer.json)
      - /home/rstudio/hetid:/home/rstudio/hetid

      # Persistent volumes for development
      - hetid-codespaces-libs:/usr/local/lib/R/site-library
      - hetid-codespaces-rstudio:/home/rstudio/.rstudio
      - hetid-codespaces-cache:/home/rstudio/.cache

      # Git configuration from Codespaces
      - /tmp/.gitconfig:/home/rstudio/.gitconfig:ro

    # Working directory
    working_dir: /home/rstudio/hetid

    # Keep container running
    stdin_open: true
    tty: true

    # Resource limits for Codespaces
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G

    # Health check optimized for Codespaces
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    # Network configuration
    networks:
      - hetid-network

# Codespaces-specific volumes
volumes:
  hetid-codespaces-libs:
    driver: local
  hetid-codespaces-rstudio:
    driver: local
  hetid-codespaces-cache:
    driver: local

networks:
  hetid-network:
    driver: bridge
