name: Codespaces Prebuild
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    # Run every Monday at 2 AM UTC
    - cron: '0 2 * * 1'

jobs:
  createPrebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Codespaces image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/heteroskedasticity-codespaces:latest
            ghcr.io/${{ github.repository_owner }}/heteroskedasticity-codespaces:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
