# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

# Set workflow-level permissions to read-only by default for security
permissions:
  contents: read

# Improved concurrency control following 2025 best practices
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name != 'pull_request' || github.run_id }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    # Job-level permissions following least-privilege principle
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        config:
          # Test with R 4.5.0 (release) and R 4.4.x (oldrel)
          - {os: ubuntu-22.04,   r: 'release'}  # R 4.5.0
          - {os: ubuntu-22.04,   r: 'oldrel'}   # R 4.4.x
          - {os: windows-latest, r: 'release'}  # R 4.5.0
          - {os: macos-latest,   r: 'release'}  # R 4.5.0
          # Optional: Add explicit version testing
          # - {os: ubuntu-22.04,   r: '4.5.0'}
          # - {os: ubuntu-22.04,   r: '4.4.3'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      # Enable CRAN incoming checks for release workflows
      _R_CHECK_CRAN_INCOMING_: ${{ github.event_name == 'release' && 'true' || 'false' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Security: Only fetch what's needed
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::remotes
          needs: check

      - name: Check R package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'
          args: 'c("--no-manual", "--as-cran")'
