name: rworkflows
# Triggers follow GitHub Flow: only on main branch and PRs to main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  rworkflows:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-latest
          bioc: devel
          r: auto
          cont: ghcr.io/bioconductor/bioconductor_docker:devel
          rspm: ~
        - os: macOS-latest
          bioc: release
          r: auto
          cont: ~
          rspm: ~
        - os: windows-latest
          bioc: release
          r: auto
          cont: ~
          rspm: ~
    steps:
      - uses: actions/checkout@v4
      - uses: neurogenomics/rworkflows@v1
        with:
          run_bioccheck: ${{ false }}
          run_rcmdcheck: ${{ true }}
          as_cran: ${{ true }}
          run_vignettes: ${{ true }}
          has_testthat: ${{ true }}
          run_covr: ${{ true }}
          run_pkgdown: ${{ false }}
          has_runit: ${{ false }}
          has_latex: ${{ false }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run_docker: ${{ true }}
