name: rworkflows
'on':
  push:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
  pull_request:
    branches:
    - master
    - main
    - devel
    - RELEASE_**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rworkflows:
    permissions:
      contents: read
      packages: write
      pull-requests: write
      statuses: write
      pages: write
      id-token: write
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-22.04
          bioc: devel
          r: auto
          cont: ghcr.io/bioconductor/bioconductor_docker:devel
          rspm: ''
        - os: macos-14
          bioc: release
          r: auto
          cont: ''
          rspm: ''
        - os: windows-2022
          bioc: release
          r: auto
          cont: ''
          rspm: ''
    steps:
    - uses: actions/checkout@v4
    - uses: neurogenomics/rworkflows@v1  # Use stable release version
      timeout-minutes: 60  # Add timeout to prevent hanging
      with:
        run_bioccheck: false
        run_rcmdcheck: true
        as_cran: true
        run_vignettes: true
        has_testthat: true
        run_covr: true
        run_pkgdown: true
        has_runit: false
        has_latex: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run_docker: false
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
