name: rworkflows
'on':
  push:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
  pull_request:
    branches:
    - master
    - main
    - devel
    - RELEASE_**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rworkflows:
    permissions:
      contents: read
      packages: write
      pull-requests: write
      statuses: write
      pages: write
      id-token: write
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-22.04
          r: release
          rspm: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        use-public-rspm: true
        
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
        
    - uses: r-lib/actions/check-r-package@v2
      with:
        upload-snapshots: true
